apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      volumes:
      containers:
      - image: sonarqube:lts
        name: sonarqube
        resources:
          limits:
            cpu: "1"
            memory: "4Gi"
        volumeMounts: 
--- 
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: demo
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: sonarqube
